### ISSUE TITLE
'tag Level does not exist' error

### ISSUE THREAD

**Issue by nillawafers4u** [Nyveon/MCStructureCleaner#10]
not 100% sure what I'm doing but when I run the script it throws this error ('tag Level does not exist') and gives a blank "new region" folder with nothing in it.

using different parameters seems to have no effect, do you have any idea of what i"m doing wrong?

**Comment by nillawafers4u** [comment]
![help](https://user-images.githubusercontent.com/67214441/147515201-ab622fdc-a42d-45f1-8856-7e801235ef18.png)

**Comment by Nyveon** [comment]
Hi, could you check the size of your r.6.-1.mca file?
Or, check if there are any .mca files with a size listed of 0 bytes.

**Comment by nillawafers4u** [comment]
r.6.-1.mca seems to be about 12mb, I went ahead and sorted by size and there's probably like 20 mca files that are 0 bytes in the region folder of my world

**Comment by Nyveon** [comment]
What version of the game is it? It could be one of two issues and I'm trying to get both of them fixed right now 🤔

**Comment by nillawafers4u** [comment]
1.18.1

**Comment by Nyveon** [comment]
Ok, try running this version of main.py and let me know if it works or not. I think this should fix the issues with 1.18. https://github.com/Nyveon/MCStructureCleaner/blob/1.5/main.py

**Comment by nillawafers4u** [comment]
Seems to run as intended now, all but 3 of the warnings I was getting for "betternether:nether_city" are gone. not really sure why the other 3 are still there but overall it seems to have done the trick

**Comment by Nyveon** [comment]
Great! Glad it's mostly working as intended. Strange that it didn't work for all tags, do you think you could send me your region folder so I could check it out and see why this would be?

**Comment by nillawafers4u** [comment]
doesnt seem to let me attach my region file, I'm new to github am I doing something wrong?

Also I took a look with NBTExplorer in the chucks that the the warnings are claiming the references are but there doesnt seem to actually be anything there anymore.

**Comment by Nyveon** [comment]
You might have to upload it somewhere else, or you can send it to me directly via discord Nyveon#9999.

But yeah... very strange. Maybe more changed in 1.18 than I thought at first.
