### ISSUE TITLE
level data not found - 1.18

### ISSUE THREAD

**Issue by notdev27** [Nyveon/MCStructureCleaner#12]
once the program finished and I put it back on my server, it basically wiped the whole world and so I restored from a backup and tried one more time and still wiped the world. The console was printing level data not found for every chunk loaded

**Comment by Nyveon** [comment]
Hmm, sound bad, going to mark it as not working in 1.18 while I try to figure this out. 

Do you think you could send me a couple of the .mca region files? From before and after. (If you don't want to upload them somewhere you can message me on discord: Nyveon#9999)

What command did you run?

**Comment by JasonJTucker** [comment]
It's not a problem with MCStructureCleaner, it's a problem with Anvil Parser and the way it writes chunks to region files. I originally tried Mauchin's fork of Anvil Parser as it had modifications to add 1.18.x support but it still didn't work correctly. My fork of Mauchin's version at https://github.com/Hai-Karate/anvil-parser with some small changes to the chunk writing code worked for myself and a few other people.

**Comment by Nyveon** [comment]
Interesting! It seems similar to what I did here https://github.com/Nyveon/MCStructureCleaner/commit/0dea4b5f947389bce012f2d396928d10fc87e511#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R69 but it seems I may have done it improperly, I will be experimenting with it shortly, thank you!

**Comment by notdev27** [comment]
> Hmm, sound bad, going to mark it as not working in 1.18 while I try to figure this out.
> 
> Do you think you could send me a couple of the .mca region files? From before and after. (If you don't want to upload them somewhere you can message me on discord: Nyveon#9999)
> 
> What command did you run?

I deleted them but im guessing it will reproduce itself still if u want me to try again

**Comment by Jadan1213** [comment]
I Just tried this as well, and it wiped out the world too, in the same way. Rolled back the snapshot and back up and running. 

1.18.1 world.
