### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by Nyveon** [Nyveon/MCStructureCleaner#14]
One of the hardest parts of using this project, is interacting with the command line for people who are not familiar with that workflow. A graphical user interface could greatly improve the experience.

The other hardest part, is the installation of python and the dependencies, for people who do not already have them installed or do not know how. Packaging the project as an executable, could greatly help streamline the usage of the software.

If anybody has ideas for how either of these should be implemented, feel free to comment them below.

Edit: Title change so that standalone executable can be a separate issue

**Comment by Morasiu** [comment]
It can be a simple UI using `tkinter`. It's ugly, but simple and works on all systems.

**Comment by Nyveon** [comment]
Tested this package out https://pypi.org/project/Gooey/ and it seems very promising. Once the 1.17+ world issues is fixed, will implement
