### ISSUE TITLE
[Feature Request] Tag name regex/wildcards

### ISSUE THREAD

**Issue by Sshmoob** [Nyveon/MCStructureCleaner#16]
I thought by tag you meant namespace, but I put in the tag "repurposed_structures" (the mod I deleted) and it keeps saying 0 tags were removed. What does it actually mean by tag?

**Comment by Nyveon** [comment]
By tag it means the exact name of the structure as defined in the region file.

To find them you can use a tool like [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases), go to the region folder, then in a .mca file open a chunk -> level -> structures -> references.

There you will see the vanilla ones, and sometimes the modded ones. You may have to check multiple different chunks to find the tags you are looking for. To use the tool, you just write the tag name exactly as it appears there.

Example:
![image](https://user-images.githubusercontent.com/54124297/166805718-c316a3e5-175a-4a5b-81c8-05fe0114f516.png)

Hope that clear everything up! I'm happy to answer any other questions as well c:

**Comment by Sshmoob** [comment]
So if I wanted to delete all references to awesome dungeons structures, the tag would be "awesomedungeon"? 
![image](https://user-images.githubusercontent.com/80718549/166832594-75343caf-691a-4fa6-bb1e-d206b04dcac7.png)

**Comment by Sshmoob** [comment]
Oh, I have to type the entire name of the tag manually, so for the first one it would be "awesomedungeon:abandoned_oak_palace". Thats annoying. I wanted to remove all awesome dungeon structures. Is there a way I can do this easier or copy the name of all the tags quickly?

**Comment by Nyveon** [comment]
I think the only easier way to do it, would be to let the script remove all non vanilla tags (the default if you don't provide a tag). That will only work if you have no mods that add structure tags though, otherwise it will remove those too.

**Comment by Sshmoob** [comment]
Is there a way to only remove structures that don't have mods for them? Or maybe you could make it so in your program I can have the tag as something like "repurposed_structures:*" and it will remove any tag that begins with repurposed_structures:. Maybe in 1.6?

**Comment by Nyveon** [comment]
The proposed feature of this issue is for more advanced tag selection parameters, I might implement this one day.
