### ISSUE TITLE
Chunk file at ___ is missing level data, skipping after running the program.

### ISSUE THREAD

**Issue by Sshmoob** [Nyveon/MCStructureCleaner#17]
After I run the program and put the world on my server, I get these messages in my logs. 
![image](https://user-images.githubusercontent.com/80718549/166859886-97d2578c-68a3-47a9-a3e5-64298f707d91.png)
I am assuming that when the program removed the structures it messed up something else in the files. I am using 1.18.

**Comment by Nyveon** [comment]
Yes, the script currently does not work for most 1.18 worlds as the warning in the description says. Sorry :(

This is currently dependent on an issue with Anvil Parser unfortunately, and I haven't gotten around to making a custom patch for 1.18.

**Comment by Sshmoob** [comment]
Turns out a different program I already had on my computer called mca selector can do the things NBTexplorer and this program can and it works in 1.18. I guess I will be using that for now.
