### ISSUE TITLE
KeyError: 'Tag Level does not exist'

### ISSUE THREAD

**Issue by Sjoelback** [Nyveon/MCStructureCleaner#26]
Trying to purge my 1.20.4 world files but getting this error.
Added the log below.

> No tag given, will run in purge mode.
> Replacing all non-vanilla structures in             all region files in G:\world\region.
> --------------------------------
> Saving newly generated region files to G:\fixed\new_region
> Checking file: G:\world\region\r.-1.-1.mca
> Checking file: G:\world\region\r.-2.2.mca
> Checking file: G:\world\region\r.-7.0.mca
> Checking file: G:\world\region\r.-1.0.mca
> Checking file: G:\world\region\r.-2.9.mca
> Checking file: G:\world\region\r.-4.1.mca
> Checking file: G:\world\region\r.1.-12.mca
> Checking file: G:\world\region\r.-1.-3.mca
> Checking file: G:\world\region\r.-6.0.mca
> Checking file: G:\world\region\r.3.-6.mca
> Checking file: G:\world\region\r.-3.8.mca
> Checking file: G:\world\region\r.-9.2.mca
> Checking file: G:\world\region\r.0.6.mca
> Checking file: G:\world\region\r.4.-2.mca
> Checking file: G:\world\region\r.5.-4.mca
> Checking file: G:\world\region\r.-2.-5.mca
> Checking file: G:\world\region\r.-5.0.mca
> Checking file: G:\world\region\r.2.2.mca
> Checking file: G:\world\region\r.-1.7.mca
> Checking file: G:\world\region\r.-3.0.mca
> Checking file: G:\world\region\r.0.-2.mca
> Checking file: G:\world\region\r.1.3.mca
> Checking file: G:\world\region\r.-2.-1.mca
> Checking file: G:\world\region\r.0.-9.mca
> Checking file: G:\world\region\r.1.-6.mca
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "C:\Users\Roy\Desktop\MCStructureCleaner_v17\structurecleaner\remove_tags.py", line 34, in _remove_tags_region_task
>     return _remove_tags_region(*args)
>   File "C:\Users\Roy\Desktop\MCStructureCleaner_v17\structurecleaner\remove_tags.py", line 95, in _remove_tags_region
>     new_region.add_chunk(anvil.Chunk(data_copy))
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\site-packages\anvil\chunk.py", line 55, in __init__
>     self.data = nbt_data['Level']
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\site-packages\nbt\nbt.py", line 543, in __getitem__
>     raise KeyError("Tag %s does not exist" % key)
> KeyError: 'Tag Level does not exist'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Roy\Desktop\MCStructureCleaner_v17\main.py", line 268, in <module>
>     main()
>   File "C:\Users\Roy\Desktop\MCStructureCleaner_v17\main.py", line 259, in main
>     remove_tags(to_replace, world_region, new_region, num_processes, mode)
>   File "C:\Users\Roy\Desktop\MCStructureCleaner_v17\structurecleaner\remove_tags.py", line 131, in remove_tags
>     count = sum(pool.map(_remove_tags_region_task, data))
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 367, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "C:\Users\Roy\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
>     raise self._value
> KeyError: 'Tag Level does not exist'

**Comment by Nyveon** [comment]
Hi! Could you send me a sample region file so I could test it to see how this might be fixed? You can upload it and share a link here or contact me on discord (My username is also Nyveon over there)

**Comment by Sjoelback** [comment]
Thanks for the reply, I've attached a region file: https://file.io/nOP1IuciMDIG

**Comment by Nyveon** [comment]
Interesting, I can't seem to replicate the error, so it might be specific to some region files. How old is this world?

**Comment by Nyveon** [comment]
Closing, solved via discord.

For anyone has the same issue and is reading this, check with `pip freeze` what version of anvil parser you have installed, and if it doesn't say @Nyveon, uninstall it with `pip uninstall` and then reinstall with the command in the readme.
