### ISSUE TITLE
Main.py

### ISSUE THREAD

**Issue by Sumneer** [Nyveon/MCStructureCleaner#3]
I only use python for really basic stuff so I may just be doing a simple mistake, but whenever I try to run main.py it instantly closes, I tried to find out what the problem was and this is what popped up. I have both the newest python installed and anvil parser. Thank you for making this program by the way!
![image](https://user-images.githubusercontent.com/41653390/106036532-5273b480-608a-11eb-9acd-c1d6d23eb70d.png)

**Comment by Nyveon** [comment]
Hi! When running the program you also need to provide it arguments telling it what to do.
so in your commandline, what you would type is for example: 
`python main.py -t "Better Mineshaft" -j 8`
If you need help, feel free to contact me on discord or twitter, and I can talk you through it c: Nyveon#7098

**Comment by Nyveon** [comment]
Solved
