### ISSUE TITLE
problems running script

### ISSUE THREAD

**Issue by Killakilla2** [Nyveon/MCStructureCleaner#6]
I can't get this to run is there any way you can help via discord?  my discord is KillaKilla#9286 you said contact you on discord but i dont see a contact

**Comment by MrAn0nym** [comment]
Is there a reason not to solve this issue here?

**Comment by Killakilla2** [comment]
no just hoping to show whats happening.  but i can send the info here.  I"m running the command sydi ottgib3 naub,ot -t "endrem" as the removed plugin being referred to by the minecraft console is endrem (end remastered) is causing all the nbt data to crash the server...  when running the script i get pretty far then i get this error 
![image](https://user-images.githubusercontent.com/88597528/136770580-bb0f1faa-02ad-4df1-98c4-a981291b546a.png)
this is on 1.17.1 and i'm on an ubuntu linux console

**Comment by Nyveon** [comment]
It might be an empty .mca file. Could you try sorting the region folder in descending order and seeing if there are any of size 0 bytes ?

**Comment by Killakilla2** [comment]
there are 3

**Comment by Killakilla2** [comment]
also its very odd because i tried to move the files into the folder that it did generate to test it and the chunks are from a different seed than my world

**Comment by Killakilla2** [comment]
ok the corrupt data was messing with the seed causing your program to generate chunks from the wrong seed so hopefully i fixed that by setting the seed in the world file to the correct seed.. at least i think.  So do I delete the empty files and run again?

**Comment by MrAn0nym** [comment]
correct

**Comment by Killakilla2** [comment]
ok that worked but when i moved the file into the server it basically reset my entire server i thouhgt it was just removing the tags.  it removed everything that was built in the world.  please help

**Comment by Killakilla2** [comment]
Is the script intended to replace the chunks or just the nbt tags? it was like 400,000 instances of the plugin in the world so basically everry chunk...

**Comment by Killakilla2** [comment]
solved.  your instructions say "Replace the contents of your region folder with the contents of new_region"  you may want to note to only replace the new files renederd.  I just swapped folders and it caused the world to regen all the other chunks.  TYSM your script may have just saved my world and server!!!

**Comment by Nyveon** [comment]
Sorry about not answering to this as you commented, had been out of the house all day. 

So yes, empty region files can cause issues unfortunately, I'll add it to the to-do to make it not crash the program (and leave this issue open as the marker for that).

Very glad you could get it to work! I'll try and re-write the readme to be a bit more clearer on that, sorry for the trouble T_T

**Comment by Nyveon** [comment]
Closed by https://github.com/Nyveon/MCStructureCleaner/pull/9 , only fixed versions pre-1.18.
